services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: wbschool
    depends_on:
      - postgres
      - kafka

    environment:
      DATABASE_URL: "host=localhost port=5432 user=user dbname=postgres password=password sslmode=disable"

    command: postgres -c ssl=off
    ports:
      - "8080:8080"

volumes:
  postgres_data: